### ISSUE TITLE
Job creation does not work

### ISSUE THREAD

**Issue by choffee** [voxpupuli/puppet-jenkins_job_builder#7]
A simple job as defined in the spec test of 

``` ruby
{ 'test' => { 'name' => 'test' } }
```

Should produce

``` yaml

---
- job:
    name: "test"
```

but instead produces

``` yaml

---
 -job:
    test:
 -job:
     name: "test"
```

**Comment by madAndroid** [comment]
I'm experiencing the same symptoms as @choffee - a hash provided via puppet DSL as:
```
$job_config = {
  'name'          => "test_job",
  'description'  => "test_job",
  'project-type' => 'freestyle',
  'builders' => [
    { 'shell' => 'bundle exec rake' },
  ],
  'triggers' => [
    { 'timed' => '*/1 * * * *' }
  ],
}
```
Results in:
```
---
- job:
    builders:
- job:
     - shell: "bundle exec rake create_dsl_script"
    description: "SEED_generate_jobs"
    name: "SEED_generate_jobs"
    project-type: "freestyle"
    triggers:
- job:
     - timed: "*/1 * * * *"
```

amending the template to the suggested 
```
<% if !@config.nil? and !@config.empty? %>
<%= [ 'job' => @config ].to_yaml %>
<%- end -%>
```
results in:
```

---
  - job:
      name: SEED_generate_jobs
      description: SEED_generate_jobs
      project-type: freestyle
      builders:
        - shell: "bundle exec rake create_dsl_script"
      triggers:
        - timed: "*/1 * * * *"
```

Interestingly, providing the config via hiera doesn't have the same symptoms, so I'm not sure exactly what's happening when `hiera()` is being called, compared to the config being set in the Puppet DSL.
